import {
  StarterKit,
  TextAlign,
  Placeholder,
  CharacterCount,
  Link,
  HorizontalRule,
  Mathematics,
  Selection,
  TrailingNode,
  Typography,
  UniqueID,
  NodeRange,
  DropPlaceholder,
  TextStyle,
  Color,
  BackgroundColor,
  Highlight,
  Underline,
  Subscript,
  Superscript,
  FontFamily,
  FontSize,
  LineHeight,
  Focus,
  Gapcursor,
  Code,
  Heading,
  Audio,
  Blockquote,
} from "./index";

export const ExtensionKit = [
  StarterKit.configure({
    link: false,
    bulletList: false,
    horizontalRule: false,
    blockquote: false,
    dropcursor: {
      color: "transparent",
      width: 0,
    },
    code: false,
    heading: false,
  }),
  Heading,
  Audio,
  Blockquote,
  TextStyle,
  Color,
  BackgroundColor,
  Highlight,
  Underline,
  Subscript,
  Superscript,
  FontFamily,
  FontSize,
  LineHeight,
  Focus.configure({
    className: "has-focus",
    mode: "all",
  }),
  Gapcursor,
  Link.configure({
    openOnClick: false,
    autolink: true,
    defaultProtocol: "https",
    protocols: [
      {
        scheme: "tel",
        optionalSlashes: true,
      },
      "mailto",
    ],
    linkOnPaste: true,
    HTMLAttributes: {
      class: "underline decoration-primary underline-offset-4 cursor-pointer",
      rel: "noopener noreferrer",
      target: "_blank",
      "data-type": "link",
    },
    isAllowedUri: (url, ctx) => {
      return ctx.defaultValidate(url) && !url.startsWith("./");
    },
  }),
  CharacterCount,
  TextAlign.configure({
    types: ["heading", "paragraph"],
  }),
  Placeholder,
  NodeRange,
  DropPlaceholder,
  HorizontalRule,
  Mathematics,
  Selection,
  Typography,
  UniqueID,
  Code,
  TrailingNode.configure({
    node: "paragraph",
    notAfter: ["paragraph"],
  }),
];

